version: "3.9"
services:
  web:
    build:
      context: docker
    volumes:
      - .:/opt/app
    ports:
      - "8000:80"
    depends_on:
      - db
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: bgmatch
      POSTGRES_PASSWORD: bgpass
